### ISSUE TITLE
"Missing required argument" error messages hides the banner

### ISSUE THREAD

**Issue by sdaclin** [cb1kenobi/cli-kit#28]
Whenever an argument validation arise, the banner disappear and the validation message "Missing required argument" is the first thing to be displayed.

**Comment by cb1kenobi** [comment]
Fixed by 98ee60a4804be881373c9f5dd2fd8260ae1258b5.

**Comment by sdaclin** [comment]
Thanks a lot, I'll test it once the next release will be made. 👍
