### ISSUE TITLE
Your homepage is wrong

### ISSUE THREAD

**Issue by wickedest** [cb1kenobi/cli-kit#7]
If you go to the npm cli-kit page and click 'homepage', the link is 404:
https://github.com/cb1kenobi/cli-kit/tree/readme#readme

The problem is "homepage" in package.json.

**Comment by ewanharris** [comment]
I think this might be a problem with the npm website? The link in the package.json is https://github.com/cb1kenobi/cli-kit#readme, which works for me. npm seems to be converting incorrectly somehow

It's also happening for other packages ([nyc](https://www.npmjs.com/package/nyc)).

There's a bug report on their (now inactive) GitHub issue tracker (https://github.com/npm/www/issues/456), and I've [filed an issue](https://npm.community/t/npm-website-link-to-a-packages-homepage-is-being-generated-incorrectly-for-github-links/344) on their new forum

**Comment by ewanharris** [comment]
Looks to be fixed on npm's side now. Closing
